version: '3.7'
services:
    api:
      restart:
          always
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - NODE_ENV=development
      environment:
        - PORT=3000
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PW=postgres
      ports:
        - 3000:3000
      depends_on:
        - postgres
      links:
        - postgres:postgres
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      command: npm run start:dev
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables